import Head from "next/head";
import Sidebar from "../components/Sidebar";
import ColoredCard from "../components/ColoredCard";
import Image from "next/image";
import SmallerColorCard from "../components/SmallerColorCard";

export default function Dashboard() {

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="flex bg-transparent text-black h-screen w-[100%]" data-theme="emerald">
        <div className="flex flex-col items-cente justify-cente py-8 w-[0%] lg:w-[20%]">
            <div className="">
                <Sidebar/>
            </div>
          </div>
          <div className="ml-5 w-[100%] lg:w-[80%] py-10 px-10 flex flex-col bg-[#f6f9ff]">
               <h6 className="text-3xl font-bold mb-5">Welcome MicroTechnologies</h6>
            <div className="flex flex-wrap">
                <div className="flex flex-row pl-10 flex-wrap items-center gap-5 rounded-lg px-4 py-7 mr-10 lg:w-[47%] border bg-white ">
                    <div className="w-[45%]"><p>Wallet Balance</p><p>$0</p></div>
                    <div className="w-[45%]"><p>No. of Devices</p><p>2</p></div>
                    <div className="w-[45%]"><p>Carbon Credits</p><p>0</p></div>
                    <div className="w-[45%]"><p>Wallet ID</p><p>NIL</p></div>
                    <button
                      type="submit"
                      className="text-white bg-green-700 flex justify-center lg:w-[95%] h-12 rounded-lg cursor-pointer px-12  items-center"
                      > Buy Carbon Credit
                    </button>
                </div>

                <div className="rounded-lg px-4 py-7 lg:w-[47%] border bg-white">
                <h6 className="text-3xl">Monthly Usage Summary</h6>
                <div className="flex md:flex-row flex-col items-center gap-5">
                    
                </div>
                </div>

                <div className="rounded-lg px-4 py-7 lg:w-[98%] mt-10 border bg-white">
                <h6 className="text-3xl">Credit Transaction / Usage</h6>
                <div className="flex md:flex-row flex-col items-center gap-5">
                    
                </div>
                </div>
            </div>
            </div>
      </main>
    </div>
  );
}
